<a href="https://colab.research.google.com/github/sakshisaxena24/Python/blob/main/Sakshi_Saxena_NLP_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <font color = dodgerred>**HW1 - 15 Points** </font>
- **You have to submit two files for this part of the HW**
  >(1) ipynb (colab notebook) and<br>
  >(2) pdf file (pdf version of the colab file).**
- **Files should be named as follows**:
>FirstName_LastName_HW_1**


In [ ]:
import torch
import time

# <font color = dodgerred>**Q1 : Create Tensor (1/2 Point)**
 Create a torch Tensor of shape (5, 3) which is filled with zeros. Modify the tensor to set element (0, 2) to 10 and element (2, 0)  to 100.

In [ ]:
my_tensor = torch.Tensor([[0,0,0],[0,0,0],[0,0,0],[0,0,0],[0,0,0]])
my_tensor[0,2]=10
my_tensor[2,0]=100

In [ ]:
my_tensor.shape

torch.Size([5, 3])

In [ ]:
my_tensor

tensor([[  0.,   0.,  10.],
        [  0.,   0.,   0.],
        [100.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]])

In [ ]:
# Manually set the value at the first row and third column to 10,
# and the value at the third row and first column to 100 in the tensor named "my_tensor".

my_tensor[1,2]=10
my_tensor[3,0]=100

In [ ]:
my_tensor

tensor([[  0.,   0.,  10.],
        [  0.,   0.,  10.],
        [100.,   0.,   0.],
        [100.,   0.,   0.],
        [  0.,   0.,   0.]])

# <font color = dodgerred>**Q2: Reshape tensor (1/2 Point)**
You have following tensor as input:

```x=torch.tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])```

Using only reshaping functions (like view, reshape, transpose, permute), you need to get at the following tensor as output:

```
tensor([[ 0,  4,  8, 12, 16, 20],
        [ 1,  5,  9, 13, 17, 21],
        [ 2,  6, 10, 14, 18, 22],
        [ 3,  7, 11, 15, 19, 23]])
```



In [ ]:
x=torch.tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [ ]:
x = x.reshape(6,4)
x = x.transpose(0,1)
x

tensor([[ 0,  4,  8, 12, 16, 20],
        [ 1,  5,  9, 13, 17, 21],
        [ 2,  6, 10, 14, 18, 22],
        [ 3,  7, 11, 15, 19, 23]])

# <font color = dodgerred>**Q3: Slice tensor (1Point)**

- Slice the tensor x to get the following
>- last row of x
>- fourth column of x
>- first three rows and first two columns - the shape of subtensor should be (3,2)
>- odd valued rows and columns

In [41]:
x = torch.tensor([[1, 2, 3, 4, 5], [6, 7, 8, 8, 10], [11, 12, 13, 14, 15]])
x

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  8, 10],
        [11, 12, 13, 14, 15]])

In [42]:
x.shape

torch.Size([3, 5])

In [43]:
# Student Task: Retrieve the last row of the tensor 'x'
# Hint: Negative indexing can help you select rows or columns counting from the end of the tensor.
# Think about how you can select all columns for the desired row.
last_row = x[-1]
last_row

tensor([11, 12, 13, 14, 15])

In [44]:

# Student Task: Retrieve the fourth column of the tensor 'x'
# Hint: Pay attention to the indexing for both rows and columns.
# Remember that indexing in Python starts from zero.
fourth_column = x[:,3]
fourth_column

tensor([ 4,  8, 14])

In [45]:
# Student Task: Retrieve the first 3 rows and first 2 columns from the tensor 'x'.
# Hint: Use slicing to extract the required subset of rows and columns.
first_3_rows_2_columns = x[0:3,0:2]
first_3_rows_2_columns

tensor([[ 1,  2],
        [ 6,  7],
        [11, 12]])

In [46]:
# Student Task: Retrieve the rows and columns with odd-indexed positions from the tensor 'x'.
# Hint: Use stride slicing to extract the required subset of rows and columns with odd indices.
odd_valued_rows_columns = x[1::2,1::2]
odd_valued_rows_columns

tensor([[7, 8]])

#  <font color = dodgerred>**Q4 -Normalize Function (1/2 Points)**<font>

Write the function that normalizes the columns of a matrix. You have to compute the mean and standard deviation of each column. Then for each element of the column, you subtract the mean and divide by the standard deviation.

In [48]:
# Given Data
x = [[ 3,  60,  100, -100],
     [ 2,  20,  600, -600],
     [-5,  50,  900, -900]]

In [49]:
# Convert to PyTorch Tensor and set to float
X = torch.tensor(x)
X= X.float()

In [50]:
# Print shape and data type for verification
print(X.shape)
print(X.dtype)

torch.Size([3, 4])
torch.float32


In [51]:
# Compute and display the mean and standard deviation of each column for reference
X.mean(axis = 0)
X.std(axis = 0)

tensor([  4.3589,  20.8167, 404.1452, 404.1452])

In [52]:
X.std(axis = 0)

tensor([  4.3589,  20.8167, 404.1452, 404.1452])

- Your task starts here
- Your normalize_matrix function should take a PyTorch tensor x as input.
- It should return a tensor where the columns are normalized.
- After implementing your function, use the code provided to verify if the mean for each column in Z is close to zero and the standard deviation is 1.

In [53]:
def normalize_matrix(x):
  # Calculate the mean along each column (think carefully , you will take mean along axis = 0 or 1)
  mean = x.mean(axis=0)

  # Calculate the standard deviation along each column
  std = x.std(axis=0)

  # Normalize each element in the columns by subtracting the mean and dividing by the standard deviation
  y = (x-mean)/std

  return y  # Return the normalized matrix



In [54]:
Z = normalize_matrix(X)
Z

tensor([[ 0.6882,  0.8006, -1.0722,  1.0722],
        [ 0.4588, -1.1209,  0.1650, -0.1650],
        [-1.1471,  0.3203,  0.9073, -0.9073]])

In [56]:
Z.mean(axis = 0),Z.std(axis = 0)

(tensor([ 0.0000e+00,  4.9671e-08,  3.9736e-08, -3.9736e-08]),
 tensor([1., 1., 1., 1.]))

# <font color = 'dodgerred'>**Q5: In-place vs. Out-of-place Operations (1 Point)**

1. Create a tensor `A` with values `[1, 2, 3]`.
2. Perform an in-place addition (use `add_` method) of `5` to tensor `A`.
3. Then, create another tensor `B` with values `[4, 5, 6]` and perform an out-of-place addition of `5`.

**Print the memory addresses of `A` and `B` before and after the operations to demonstrate the difference in memory usage. Provide explanation**


In [ ]:
A = torch.tensor([1, 2, 3])
print('Original memory address of A:',id(A))
A+=5
print('Memory address of A after in-place addition:', id(A))
print('A after in-place addition:', A)

B = torch.tensor([4, 5, 6])
print('Original memory address of B:', id(B))
B = B.add(1)
print('Memory address of B after out-of-place addition:', id(B))
print('B after out-of-place addition:', B)


Original memory address of A: 135148777515152
Memory address of A after in-place addition: 135148777515152
A after in-place addition: tensor([6, 7, 8])
Original memory address of B: 135148777509312
Memory address of B after out-of-place addition: 135148777516272
B after out-of-place addition: tensor([5, 6, 7])


**Provide Explanation for above question here :**


1.  Inplace operations modify the data in the original tensor, while outplace
operations create a new tensor with the modified data.
2.  When an inplace operation is performed, the memory address of the original tensor does not change. This is because the data in the tensor is being modified in-place.
3. When an outplace operation is performed, a new tensor is created with the modified data. This means that the memory address of the new tensor will be different from the memory address of the original tensor.





# <font color = 'dodgerred'>**Q6: Tensor Broadcasting (1 Point)**

1. Create two tensors `X` with shape `(3, 1)` and `Y` with shape `(1, 3)`. Perform an addition operation on `X` and `Y`.
2. Explain how broadcasting is applied in this operation by describing the shape changes that occur internally.

In [ ]:
X = torch.randint(high=10,size=(3,1))
Y = torch.randint(high=10,size=(1,3))
print('Original shapes:', X.shape, Y.shape)
result = X+Y
print('Result:', result)
print('Result shape:', result.shape)


Original shapes: torch.Size([3, 1]) torch.Size([1, 3])
Result: tensor([[ 3,  8,  9],
        [ 5, 10, 11],
        [ 5, 10, 11]])
Result shape: torch.Size([3, 3])


**Provide Explanation for above question here :**
Tensor X has size (3, 1), which means that it has 3 rows and 1 column.
Tensor Y has size (1, 3), which means that it has 1 row and 3 columns.
To perform the addition operation, PyTorch will expand the size of tensor Y to (3, 3) by duplicating its rows. This means that the new tensor Y will have 3 rows and 3 columns.
The addition operation will then be performed between the two tensors, resulting in a new tensor 'result' with size (3, 3).



# <font color = 'dodgerred'>**Q7: Linear Algebra Operations (1 Point)**

1. Create two matrices `M1` and `M2` of compatible shapes for matrix multiplication. Perform the multiplication and print the result.
2. Then, create two vectors `V1` and `V2` and compute their dot product.


In [ ]:
M1 = torch.arange(0, 10, dtype=int).reshape(2, 5)
M2 = torch.arange(0, 10, dtype=int).reshape(5,2)
mat_multiplication =  torch.mm(M1,M2)
print('Matrix multiplication result:', mat_multiplication)

V1 = torch.tensor([1, 2, 3])
V2 =  torch.tensor([4, 5, 6])
dot_product =  torch.dot(V1,V2)
print('Dot product:', dot_product)


Matrix multiplication result: tensor([[ 60,  70],
        [160, 195]])
Dot product: tensor(32)


# <font color = 'dodgerred'>**Q8: Manipulating Tensor Shapes (1 Point)**

Given a tensor `T` with shape `(2, 3, 4)`, demonstrate how to
1. reshape it to `(3, 8)` using view,
2. reshape it to `(4, 2, 3` using reshape,
3. transpose the first and last dimensions using permute.
4. explain what is the difference between reshape and view

In [ ]:
T = torch.rand(2, 3, 4)
T_view =  T.view(3,8)
print('T_view shape:', T_view.shape)

T_reshape =  T.reshape(4,2,3)
print('T_reshape shape:', T_reshape.shape)

T_permute =  T.permute(2,1,0)
print('T_permute shape:', T_permute.shape)

T_view shape: torch.Size([3, 8])
T_reshape shape: torch.Size([4, 2, 3])
T_permute shape: torch.Size([4, 3, 2])


**Provide Explanation for above question here :**
1. reshape() creates a new array with the specified shape ex: from (2,3,4) to (4,2,3) and the shape of the original array is not modified . The original tensor(T) and reshaped tensor have different memory locations.
2. view() creates a new view or snapshot of the original array with the specified shape, the original tensor and view share the same memory location and changed made to view will also be reflected in the original tensor



# <font color = 'dodgerred'>**Q9: Tensor Concatenation and Stacking (1 Point)**

Create tensors `C1` and `C2` both with shape (2, 3).
1. Concatenate them along dimension 0 and then along dimension 1. Print the shape of the resulting tensor.
2. Afterwards, stack the same tensors alomng dimension 0  and print the shape of the resulting tensor.
3. What is the difference between stacking and concatinating.

In [ ]:
C1 = torch.rand(2, 3)
C2 = torch.rand(2, 3)
concatenated_dim0 =  torch.cat((C1,C2),dim=0)
print('Concatenated along dimension 0:', concatenated_dim0.shape)

concatenated_dim1 =  torch.cat((C1,C2),dim=1)
print('Concatenated along dimension 1:', concatenated_dim1.shape)

stacked =  torch.stack((C1,C2))
print('Stacked tensor shape:', stacked.shape)


Concatenated along dimension 0: torch.Size([4, 3])
Concatenated along dimension 1: torch.Size([2, 6])
Stacked tensor shape: torch.Size([2, 2, 3])


**Explain the diffrence between concatinating and stacking here**
1. concatenate (we use torch.cat()):


*   Combines two or more tensors along a specified dimension.
*   The tensors to be concatenated must have the same shape in all dimensions except the one along which they are being concatenated.
The resulting tensor will have the same data type as the input tensors.

2. stacking (we use torch.stack()):


*   Combines two or more tensors along a new dimension.
*   The tensors to be stacked can have different shapes.


*   The resulting tensor will have a new dimension with size equal to the number of tensors being stacked.











# <font color = 'dodgerred'>**Q10: Advanced Indexing and Slicing (1 Point)**

1. Given a tensor `D` with shape (6, 6), extract elements that are greater than 0.5.
2. Then, extract the second and fourth rows from `D`.
3. Finally, extract a sub-tensor from the top-left 3x3 block.

In [ ]:
D = torch.rand(6, 6)
print('Elements greater than 0.5:\n',  D[D>0.5])

second_fourth_rows =  D[[1,3],:]
print('\nSecond and fourth rows:\n',second_fourth_rows )

top_left_3x3 =  D[:3,:3]
print('\nTop-left 3x3 block:\n ',top_left_3x3 )


Elements greater than 0.5:
 tensor([0.8284, 0.9739, 0.8381, 0.8493, 0.5710, 0.5275, 0.8195, 0.7178, 0.8618,
        0.8718, 0.8728, 0.7968, 0.7523])

Second and fourth rows:
 tensor([[0.8381, 0.1746, 0.3569, 0.8493, 0.2706, 0.5710],
        [0.1272, 0.4515, 0.3195, 0.1623, 0.3182, 0.0464]])

Top-left 3x3 block:
  tensor([[0.0924, 0.3603, 0.2879],
        [0.8381, 0.1746, 0.3569],
        [0.5275, 0.8195, 0.3856]])


# <font color = 'dodgerred'>**Q11: Tensor Mathematical Operations (1 Point)**

1. Create a tensor `G` with values from 0 to π in steps of π/4.
2. Compute and print the sine, cosine, and tangent logarithm and the exponential of `G`.

In [ ]:
import math

G = torch.arange(0,math.pi+0.00001,math.pi/4)
print('G:', G)
print('Sine of G:',  torch.sin(G))
print('Cosine of G:',  torch.cos(G))
print('Tangent of G:',  torch.tan(G))
print('Natural logarithm of G:',  torch.log(G))
print('Exponential of G:',  torch.exp(G))


G: tensor([0.0000, 0.7854, 1.5708, 2.3562, 3.1416])
Sine of G: tensor([ 0.0000e+00,  7.0711e-01,  1.0000e+00,  7.0711e-01, -8.7423e-08])
Cosine of G: tensor([ 1.0000e+00,  7.0711e-01, -4.3711e-08, -7.0711e-01, -1.0000e+00])
Tangent of G: tensor([ 0.0000e+00,  1.0000e+00, -2.2877e+07, -1.0000e+00,  8.7423e-08])
Natural logarithm of G: tensor([   -inf, -0.2416,  0.4516,  0.8570,  1.1447])
Exponential of G: tensor([ 1.0000,  2.1933,  4.8105, 10.5507, 23.1407])


# <font color = 'dodgerred'>Q12: **Tensor Reduction Operations (1 Point)**

1. Create a 3x2 tensor `H`.
2. Compute the sum of `H`. Print the result and shape after taking sun.
3. Then, perform the same operations along dimension 0 and dimension 1, printing the results and shapes.
4. What do you observe? How the shape changes?

In [ ]:
H = torch.rand(3, 2)
print('H:', H, end = "\n\n")
print('Shape of original Tensor H', H.shape, end = "\n\n")

print('Sum of H:',  torch.sum(H))
print('Shape after Sum of H:', torch.sum(H).shape,end = "\n\n" )

print('Sum of H along dimension 0:',  torch.sum(H,dim=0))
print('Shape after sum of H along dimension 0:', torch.sum(H,dim=0).shape,  end = "\n\n")

print('Sum of H along dimension 1:', torch.sum(H,dim=1))
print('Shape after sum of H along dimension 1:',  torch.sum(H,dim=1).shape)


H: tensor([[0.5742, 0.9521],
        [0.9449, 0.1377],
        [0.1474, 0.3927]])

Shape of original Tensor H torch.Size([3, 2])

Sum of H: tensor(3.1490)
Shape after Sum of H: torch.Size([])

Sum of H along dimension 0: tensor([1.6664, 1.4825])
Shape after sum of H along dimension 0: torch.Size([2])

Sum of H along dimension 1: tensor([1.5263, 1.0826, 0.5401])
Shape after sum of H along dimension 1: torch.Size([3])


**Provide your observations on shape changes here**

*   After taking the sum of all elements in H, the shape of the resulting tensor becomes torch.Size([]). This is because the sum operation reduces the tensor to a single scalar value.

*  After summing along dimension 0 or dimension 1, the shape of the resulting tensor changes depending on the dimension along which the sum is performed.


*   The sum along dimension 0 results in a tensor with shape with the same number of columns as original tensor
*   The sum along dimension 1 results in a tensor with shape with the same number of rows as original tensor







# <font color = 'dodgerred'>**Q13: Working with Tensor Data Types (1 Point)**

1. Create a tensor `I` of data type float with values `[1.0, 2.0, 3.0]`.
2. Convert `I` to data type int and print the result.
3. Explain in which scenarios it's necessary to be cautious about the data type of tensors.

In [ ]:
# Solution for Q16
I =  torch.tensor([1.0,2.0,3.0],dtype=torch.float)
print('I:', I)
I_int =  I.to(dtype=torch.int)
print('I converted to int:', I_int)

I: tensor([1., 2., 3.])
I converted to int: tensor([1, 2, 3], dtype=torch.int32)


**Your explanations here**
1. Mixing tensors with different data types can lead to unexpected results. For example, if you add a float tensor to an int tensor, the result will be a float tensor, and any fractional part of the int values will be lost.
2. When comparing tensors, it is important to ensure that the tensors have the same data type. Otherwise, the comparison may not work correctly. For example, if you compare a float tensor to an int tensor, the comparison will be performed using integer comparison rules
3. In some cases, using tensors with different data types can lead to errors. For example, if you try to index a tensor with a float index, you will get an error.



# <font color = 'dodgerred'>**Q14. Speedtest for vectorization 1.5 Points** </font>

Your goal is to measure the speed of linear algebra operations for different levels of vectorization.

1. Construct two matrices $A$ and $B$ with Gaussian random entries of size $1024 \times 1024$.
1. Compute $C = A B$ using matrix-matrix operations and report the time. (Hint: Use torch.mm)
1. Compute $C = A B$, treating $A$ as a matrix but computing the result for each column of $B$ one at a time. Report the time. (hint use torch.mv inside a for loop)
1. Compute $C = A B$, treating $A$ and $B$ as collections of vectors. Report the time. (Hint: use torch.dot inside nested for loop)

In [ ]:
## Solution 1
torch.manual_seed(42) # dod not chnage this
A = torch.randn(1024,1024)
B = torch.randn(1024,1024)

In [ ]:
## Solution 2
start=time.time()

C = torch.mm(A,B)

print("Matrix by matrix: " + str(time.time()-start) + " seconds")

Matrix by matrix: 0.031682491302490234 seconds


In [ ]:

## Solution 3
C= torch.empty(1024,1024)
start = time.time()

for i in range(B.shape[1]):
  C[:,i]= torch.mv(A,B[:,i])

print("Matrix by vector: " + str(time.time()-start) + " seconds")

Matrix by vector: 0.34830379486083984 seconds


In [ ]:
## Solution 4
C= torch.empty(1024,1024)
start = time.time()

for i in range(A.shape[0]):
  for j in range(B.shape[1]):
    C[i,j]=torch.dot(A[i,:],B[:,j])

print("vector by vector: " + str(time.time()-start) + " seconds")

vector by vector: 27.56131887435913 seconds


# <font color = 'dodgerred'>**Q15 : Redo Question 14 by using GPU - 1.5 Points**

<font size = 4, color = 'dodgerred'> **Using GPUs**

How to use GPUs in Google Colab<br>
In Google Colab -- Go to Runtime Tab at top -- select change runtime type -- for hardware accelartor choose GPU

In [ ]:
# Check if GPU is availaible
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
print(device)

cuda:0


In [ ]:
## Solution 1
torch.manual_seed(42)
A= torch.randn((1024, 1024),device=device)
B= torch.randn((1024, 1024),device=device)

In [ ]:
## Solution 2
start=time.time()

C = torch.mm(A,B)

print("Matrix by matrix: " + str(time.time()-start) + " seconds")

Matrix by matrix: 0.005873680114746094 seconds


In [ ]:
## Solution 3
C= torch.empty(1024,1024, device = device)
start = time.time()

for i in range(B.shape[1]):
  C[:,i]= torch.mv(A,B[:,i])

print("Matrix by vector: " + str(time.time()-start) + " seconds")

Matrix by vector: 0.08398818969726562 seconds


In [ ]:
## Solution 4
C= torch.empty(1024,1024, device = device)
start = time.time()

for i in range(A.shape[0]):
  for j in range(B.shape[1]):
    C[i,j]=torch.dot(A[i,:],B[:,j])
print("vector by vector: " + str(time.time()-start) + " seconds")

vector by vector: 42.38092017173767 seconds
